### ISSUE TITLE
APM : rounding number could be improved

### ISSUE THREAD

**Issue by jpcaruana** [HowFast/roadmap#14]
I think no decimals are needed (or only two) in the detailed view:

- AVG values : 

<img width="203" alt="image" src="https://user-images.githubusercontent.com/31649/64632119-c7444100-d3f8-11e9-9111-f24096c860f9.png">

- all values : 

<img width="673" alt="image" src="https://user-images.githubusercontent.com/31649/64632214-f5c21c00-d3f8-11e9-9dcd-cc3269ce79e2.png">

**Comment by MickaelBergem** [comment]
So I had almost forgot the basics of float manipulation:

```
$ node
> 16.037 * 1000
16036.999999999998
```

This is because JS represents decimal numbers as floats - Python does the same. Values are returned by the API as seconds, and are then multiplied by `1000` to display them as milliseconds. This operation causes the imprecise floating point storage method to reveal its flaws on some very specific values (including 16.037).

This will be fixed next time you refresh the frontend application (for your curiosity, rounding the number after that `* 1000` operation solves the issue).

**Comment by MickaelBergem** [comment]
Issue should now be solved. Please re-open if the issue still exists.

**Comment by jpcaruana** [comment]
Thanks ! Seems right now !
